export const zodiakList = [
  {
    id: 1,
    name: 'Cancer',
    img: 'cancer.svg',
    imgGreen: 'cancer--green.svg',
    date: [622, 722],
  },
  {
    id: 2,
    name: 'Leo',
    img: 'leo.svg',
    imgGreen: 'leo--green.svg',
    date: [723, 821],
  },
  {
    id: 3,
    name: 'Virgo',
    img: 'virgo.svg',
    imgGreen: 'virgo--green.svg',
    date: [822, 923],
  },
  {
    id: 4,
    name: 'Libra',
    img: 'libra.svg',
    imgGreen: 'libra--green.svg',
    date: [924, 1023],
  },
  {
    id: 5,
    name: 'Scorpio',
    img: 'scorpio.svg',
    imgGreen: 'scorpio--green.svg',
    date: [1024, 1122],
  },
  {
    id: 6,
    name: 'Sagittarius',
    img: 'sagittarius.svg',
    imgGreen: 'sagittarius--green.svg',
    date: [1123, 1222],
  },
  {
    id: 7,
    name: 'Capricorn',
    img: 'capricorn.svg',
    imgGreen: 'capricorn--green.svg',
    date: [1223, 120],
  },
  {
    id: 8,
    name: 'Aquarius',
    img: 'aquarius.svg',
    imgGreen: 'aquarius--green.svg',
    date: [121, 219],
  },
  {
    id: 9,
    name: 'Pisces',
    img: 'pisces.svg',
    imgGreen: 'pisces--green.svg',
    date: [220, 320],
  },
  {
    id: 10,
    name: 'Aries',
    img: 'aries.svg',
    imgGreen: 'aries--green.svg',
    date: [321, 420],
  },
  {
    id: 11,
    name: 'Taurus',
    img: 'taurus.svg',
    imgGreen: 'taurus--green.svg',
    date: [421, 521],
  },
  {
    id: 12,
    img: 'gemini.svg',
    imgGreen: 'gemini--green.svg',
    name: 'Gemini',
    date: [522, 621],
  },
];
