export default {
  commentsCounterText: 'komentářů',
  placeholder: 'přidat komentář',
  alert: `Děkujeme za váš komentář! Vaše zpráva je právě schvalována moderátory.  `,
  comments: [
    {
      avatar: '1.jpg',
      login: 'NAta',
      likes: 32,
      time: '',
      text: 'Moje IQ je 78 😐',
    },
    {
      avatar: '2.jpg',
      login: 'toster-baster',
      likes: 11,
      time: '',
      text: '139',
    },
    {
      avatar: '3.jpg',
      login: 'RaY',
      likes: 2,
      time: '',
      text: 'Moje IQ je 89 v Mensa testu to je 77',
    },
    {
      avatar: '4.jpg',
      login: '_mila',
      likes: 49,
      time: '',
      text: 'Já mám IQ 98 a moje sestra 114🥺',
    },
    {
      avatar: '5.jpg',
      login: 'kailoWest',
      likes: 21,
      time: '',
      text: '123😊',
    },
    {
      avatar: '6.jpg',
      login: 'Alikz',
      likes: 32,
      time: '',
      text: 'Test jsem prošel za dvě minuty, jsem v pohodě, IQ 119😎',
    },
    {
      avatar: '7.jpg',
      login: 'Chica Bomb',
      likes: 112,
      time: '',
      text: 'Vtipný test, ani jsem nečekal, že nasbírám tolik bodů (P.s. je to 145) :)',
    },
    {
      avatar: '8.jpg',
      login: 'trasher',
      likes: 7,
      time: '',
      text: 'Není to fér, otázky se mi moc líbily, myslel jsem, že získám vysoké skóre. Bylo podprůměrné. Měl bych číst více knih.',
    },
    {
      avatar: '9.jpg',
      login: '_mia_ma',
      likes: 2,
      time: '',
      text: '85😢😢😢',
    },
    {
      avatar: '10.jpg',
      login: 'Tweety',
      likes: 10,
      time: '',
      text: 'Cool!! 120😋',
    },
  ],
};
